services:
    netgen_information_collection.controller.admin:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\AdminController
        parent: ezpublish.controller.base
        public: true
        arguments:
            - "@netgen_information_collection.api.service"
            - "@netgen_information_collection.anonymizer.service"
            - "@ezpublish.api.service.content"
            - "@ezpublish.config.resolver"
            - "@netgen_information_collection.core.export.registry"

    netgen_information_collection.controller.export:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\ExportController
        parent: ezpublish.controller.base
        public: true
        arguments:
            - "@ezpublish.api.service.content"
            - "@netgen_information_collection.service.exporter"
            - "@netgen_information_collection.core.export.registry"

    netgen_information_collection.api.service:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Service\InformationCollectionService
        public: true
        arguments:
            - "@netgen_information_collection.repository.ez_info_collection"
            - "@netgen_information_collection.repository.ez_info_collection_attribute"
            - "@ezpublish.api.repository"
            - "@netgen_information_collection.core.persistence.gateway.doctrine"

    netgen_information_collection.controller.tree:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\TreeController
        parent: ezpublish.controller.base
        public: true
        arguments:
            - "@netgen_information_collection.api.service"
            - "@translator"
            - "@router"
            - "@ezpublish.translation_helper"

    netgen_information_collection.templating.admin_global_variable:
        class: Netgen\Bundle\InformationCollectionBundle\Templating\Twig\AdminGlobalVariable
        public: true
        arguments:
            - "@ezpublish.config.resolver"

    netgen_information_collection.core.persistence.gateway.doctrine:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Persistence\Gateway\DoctrineDatabase
        public: false
        arguments:
            - '@database_connection'

    netgen_information_collection.pagerfanta.view.eztags_admin:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Pagination\Pagerfanta\View\InformationCollectionAdminView
        public: false
        # Not being lazy results in out of memory exceptions on eZ Platform 2.0,
        # probably due to @twig dependency
        lazy: true
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, ['@@NetgenInformationCollection/admin/pagerfanta.html.twig']]
        tags:
            - { name: pagerfanta.view, alias: netgen_information_collection_admin }

    netgen_information_collection.service.exporter:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Service\ExporterService
        arguments:
            - "@netgen_information_collection.repository.ez_info_collection"
            - "@netgen_information_collection.repository.ez_info_collection_attribute"
            - "@translator"
            - "@netgen_information_collection.utils.content_type"

    netgen_information_collection.utils.content_type:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Persistence\ContentTypeUtils
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.content"

    netgen_information_collection.core.export.registry:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Export\ExportResponseFormatterRegistry

    netgen_information_collection.core.export.fomatter.csv:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Export\CsvExportResponseFormatter
        arguments:
            - "@ezpublish.translation_helper"
            - "@ezpublish.config.resolver"
        tags:
            - { name: netgen_information_collection.export.formatter }

    netgen_information_collection.core.export.formatter.xls:
        class: Netgen\Bundle\InformationCollectionBundle\Core\Export\XlsExportResponseFormatter
        arguments:
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_information_collection.export.formatter }

    netgen_information_collection.form.type.export:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Type\ExportType
        arguments:
            - "@netgen_information_collection.core.export.registry"
        tags:
            - { name: form.type }

    netgen_information_collection.form.data_mapper.info_collection:
        class: Netgen\Bundle\InformationCollectionBundle\Form\DataMapper\InformationCollectionUpdateMapper
        public: false
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen_information_collection.form.type.information_collection_update:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Type\InformationCollectionUpdateType
#        public: false
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen_information_collection.form.data_mapper.info_collection"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: form.type, alias: ezforms_information_collection_update }
